train:
  _target_: src.datasets.AVSSDataset
  data_dir: "/Users/aleksandr/Downloads/avss_test"
  index_dir: "/Users/aleksandr/Downloads/avss_test"
  split: "val"
  max_audio_length: 20.0
  limit: 2
  instance_transforms: ${transforms.instance_transforms.train}
# we filter partitions in one batch test to check the pipeline
# do not filter test dataset, you want to evaluate on the whole dataset
val:
  _target_: src.datasets.AVSSDataset
  data_dir: "/Users/aleksandr/Downloads/avss_test"
  index_dir: "/Users/aleksandr/Downloads/avss_test"
  split: "val"
  max_audio_length: 20.0
  limit: 2
  instance_transforms: ${transforms.instance_transforms.inference}
