train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.SI_SNRiMetric
    name: "SI_SNRi" # it is better to avoid spaces in names
  - _target_: src.metrics.SDRiMetric
    name: "SDRi"
  - _target_: src.metrics.PESQMetric
    name: "PESQ"
  - _target_: src.metrics.STOIMetric
    name: "STOI"
